from shared.db.entity.base import Base
from shared.db.entity.base import Base
from shared.db.entity.detection import Detection
from shared.db.entity.event_analytics import EventAnalytics
from shared.db.entity.event_article import EventArticle
from shared.db.entity.event import Event
from shared.db.entity.processed_article import ProcessedArticle
from shared.db.entity.raw_article import RawArticle
from shared.db.entity.source import Source